version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 713881787829.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t flask-app .
      - docker tag flask-app:latest 713881787829.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 713881787829.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
      - echo Writing image definitions file...
      - echo '[{"name":"flask-container","imageUri":"713881787829.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
